/** Auto-generated by scripts/sync-supabase-config.mjs — do not edit by hand */
export const BUILD_SUPABASE_URL = 'https://your-project.supabase.co'
export const BUILD_SUPABASE_ANON_KEY = 'your-anon-key'
export const BUILD_WEBSITE_URL = ''
export const BUILD_BILLING_API_URL = 'http://localhost:4242'
